defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  allow_dynamic_fields: false # When attributes are not defined as fields but added to an object, they will get fields added for them dynamically and will get persisted. This defaults to true, and if set to false an error will get raised when attempting to set a value that has no field defined. 
  parameterize_keys: true # Tells Mongoid to convert basic special characters in composite keys to SEO friendly substrings. Defaults to true. 
  persist_in_safe_mode: true # Tells Mongoid to perform all database operations in MongoDB's safe mode. This will cause the driver to double check operations and raise an error if they failed. Defaults to true, switching to false will be unsafe but will be a performance gain.
  raise_not_found_error: true # Will raise a Mongoid::Error::DocumentNotFound when attempting to find a document by an id that doesnt exist. Defaults to true, but when set to false will only return nil for the same query. 
  reconnect_time: 3 # Tells Mongoid the max time to attempt reconnection to the database if a connection failure has occured. Default is 3 seconds
  use_object_ids: false # Tells Mongoid to use BSON::ObjectID objects as ids instead of their string values.
  
development:
  <<: *defaults
  database: myapp_development #change name here!!!

test:
  <<: *defaults
  database: myapp_test #set name here!!!

# set these environment variables on your prod server
production:
  <<: *defaults
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>