class User
  include Mongoid::Document
  
  # List of fields generated by default after first sign-up. Add any additional fields you may need.
  field :first_name # extra field not created by devise
  field :last_name # extra field not created by devise
  field :birthday, :type => Date # extra field not created by devise
  field :email # will be created by default with the devise module listed below -> can delete this line
  field :sign_in_count, :type => Integer # will be created by default with the devise module listed below -> can delete this line
  field :current_sign_in_ip # will be created by default with the devise module listed below -> can delete this line
  field :encrypted_password # will be created by default with the devise module listed below -> can delete this line
  field :failed_attempts, :type => Integer # will be created by default with the devise module listed below -> can delete this line
  field :last_sign_in_at, :type => DateTime # will be created by default with the devise module listed below -> can delete this line
  field :last_sign_in_ip # will be created by default with the devise module listed below -> can delete this line
  field :password_salt # will be created by default with the devise module listed below -> can delete this line
  
  # Enable Devise Modules:
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable
         # Include default devise modules. Others available are:
         # :token_authenticatable, :confirmable, :lockable and :timeoutable
         # Database Authenticatable: encrypts and stores a password in the database to validate the authenticity of an user while signing in. The authentication can be done both through POST requests or HTTP Basic Authentication.
         # Token Authenticatable: signs in an user based on an authentication token (also known as "single access token"). The token can be given both through query string or HTTP Basic Authentication.
         # Confirmable: sends emails with confirmation instructions and verifies whether an account is already confirmed during sign in.
         # Recoverable: resets the user password and sends reset instructions.
         # Registerable: handles signing up users through a registration process, also allowing them to edit and destroy their account.
         # Rememberable: manages generating and clearing a token for remembering the user from a saved cookie.
         # Trackable: tracks sign in count, timestamps and IP address.
         # Timeoutable: expires sessions that have no activity in a specified period of time.
         # Validatable: provides validations of email and password. It’s optional and can be customized, so you’re able to define your own validations.
         # Lockable: locks an account after a specified number of failed sign-in attempts. Can unlock via email or after a specified time period.

end
